### PR TITLE
Fix calculation of aggregate_version

### PR DESCRIPTION
**Pull request by CptBreeza**
Address https://github.com/commanded/commanded/issues/353

### CODE REVIEW

**Comment by slashdotdash** [comment]
Thanks for the pull request. I want to consider if there are any other implications of using `event_number` instead of `stream_version` as the aggregate's version before merging.

**Comment by CptBreeza** [comment]
> Thanks for the pull request. I want to consider if there are any other implications of using `event_number` instead of `stream_version` as the aggregate's version before merging.

Thanks.

**Comment by vasspilka** [comment]
We will not be using same streams across different eventstores ever correct?
For new applications this would not be a problem at all, would running applications have a chance to process events not in order if they where to upgrade?

**Comment by CptBreeza** [comment]
So is there any progress on this?

**Pull request closed without merging**
