### PR TITLE
Implement event upcasting.

### PR DESCRIPTION
**Pull request by trbngr**
A quick stab at #258

### CODE REVIEW

**Comment by slashdotdash** [comment]
Thanks for the pull request, this looks like a good start. 

It’s worth noting that events published to subscribers, such as event handlers and process managers, won’t go through the stream forward function. To solve this issue the `Commanded.EventStore` behaviour will need to be extended to allow a mapper function to be provided to both stream forward and subscribe to stream so that the upcasting can happen in both places.

**Comment by trbngr** [comment]
Thanks Ben. Good catch. I'd like to investigate this further before you merge it.

**Comment by trbngr** [comment]
I think the latest commit addresses your concerns and will not required tweaking on the ES adapters.

As I believe this is `commanded` only feature, we should be good.

**Comment by trbngr** [comment]
Oh! And I fixed a bug in the `InMemory` adapter. It was enuming over the stream and therefore executing the event_stream.

**Comment by trbngr** [comment]
I wonder if `stream_forward` is the right place for the upcast. I'm thinking it should really be in `Aggregate.handle_info({:events, events}, _)` like the others.

Thoughts?

**Comment by slashdotdash** [comment]
> Aggregate.handle_info({:events, events}, _)

Is only used for transient subscriptions to the configured event store which means it will never receive historical events so no upcasting is required.

Having the upcast applied in `stream_forward` is useful because it allows consumers to read from the configured event store if they need to.

**Comment by slashdotdash** [comment]
@trbngr Is this PR ready to merge now?

**Comment by trbngr** [comment]
That's your call, bud. I am done with it

**Pull request merged**
