### PR TITLE
Add credo code analysis

### PR DESCRIPTION
**Pull request by aleDsz**
It's just a simple PR to implement an useful tool to preserve the good code quality

### CODE REVIEW

**Comment by slashdotdash** [comment]
@aleDsz I'm not keen on making such large changes to the codebase based upon Credo recommendations. My concern is introducing bugs or subtle changes in behaviour during refactoring.

**Comment by aleDsz** [comment]
@slashdotdash If I split all these changes into little PRs, would be a better way to all this changes be merged?

**Comment by slashdotdash** [comment]
I'm not sure what value the proposed changes add. For example they include adding many new functions which only have a single line in the function body. I'd prefer not to need to strictly follow conventions dictated by a tool such as Credo when they don't make they code easier to reason about or follow.

**Comment by aleDsz** [comment]
> I'm not sure what value the proposed changes add. For example they include adding many new functions which only have a single line in the function body. I'd prefer not to need to strictly follow conventions dictated by a tool such as Credo when they don't make they code easier to reason about or follow.

The proposal is to standardize the entire style guide used in the project, so that there are no parts of the code that are so different from the rest of the project.

The idea is not to bring meaningless modifications, since some functions are very complex, I had to change them so that the public functions were just "endpoints" of a flow of private functions to perform the pattern matching of existent `case... do` blocks.

The "value" of these changes would be to make it easier for those who want to contribute to the project (like me) and for them to write code that is still in the style in which the project currently operates.

If it is not of interest to everyone, I will understand and will not open PR to implement the use of `credo`.

Now, about `credo`, we can disable certain checks made by `credo` so that the project can create its own style of code and check only what everyone understands to be paramount and remove those that don't make much sense to the project. Or, we can change how complex a function should be and things like that.

**Comment by slashdotdash** [comment]
My preference is to follow the existing coding style and strive to continuously improve the code when making changes. The "leave it better than you found it" principle.

**Comment by slashdotdash** [comment]
If you feel Credo really adds value then submit a PR where it is added as an optional Mix dependency only. Don't include it in the GitHub Actions workflow, nor include any suggested code refactoring. Then I can include the appropriate rules as required.

**Comment by aleDsz** [comment]
> If you feel Credo really adds value then submit a PR where it is added as an optional Mix dependency only. Don't include it in the GitHub Actions workflow, nor include any suggested code refactoring. Then I can include the appropriate rules as required.

Sure

**Pull request closed without merging**
