### PR TITLE
Use TypeProvider for process managers snapshot serialization

### PR DESCRIPTION
**Pull request by vheathen**
Addresses #538

### CODE REVIEW

**Comment by drteeth** [comment]
I think this change makes sense when you look at it on it's own. While it seems like a no brainer for the greenfield case, if it is accepted, what will it do when people upgrade?

It seems like the for the default case, `Commanded.Serialization.ModuleNameTypeProvider` will not be affected, but for anyone using a custom TypeProvider, will it not break their ProcessManager state?

Is there something we could do to alert users of custom type providers that we're about to break the contract (for the better)?

**Review by drteeth — CHANGES_REQUESTED** [review]
We need to consider how to roll this change out

**Comment by vheathen** [comment]
@drteeth sorry for the long reaction.

I agree that we need to communicate about this. My initial thought was to mention it in the changelog, but I'm not sure it will be enough. 

Of course, it is possible to introduce a separate configuration parameter to enable `TypeProvider` for process managers and keep the default behaviour intact, but it looks a bit heavy.

**Comment by drteeth** [comment]
While trying to think through a valid migration path, I think I've come to agree with @jvantuyl in that the only people this would affect are people that would have worked around it. I think we should just go ahead and make the change.

**Comment by drteeth** [comment]
The only other thing I'd like to see is a test that fails with the existing behaviour and then is resolved by making the change you are recommending. The idea being that we don't break it again in the future.

**Comment by vheathen** [comment]
The only reason I didn't include tests is that I didn't find any tests for the actual `TypeProvider` usage, only the unit tests for the `ModuleNameTypeProvider`.

But of course, it's always better to have tests. Please check the included one.

**Review by drteeth — APPROVED** [review]

**Review by cdegroot — APPROVED** [review]

**Pull request merged**
