### PR TITLE
Process manager metadata read access

### PR DESCRIPTION
**Pull request by vheathen**
The PR addresses #440 and allows metadata read access from all callbacks except `error/3` (as the last one already has access to full RecordedEvent struct).

Supports both old and new callback versions (with and without metadata as the last parameter)

Also adds copying metadata from processed events to new commands by default. 

Modification of the metadata inside the process manager `handle/3` and `handle/2` callbacks are subject of the possible next PR.

### CODE REVIEW

**Review by jwilger — APPROVED** [review]
@slashdotdash Any objections to getting this merged in? I actually came here today thinking about making the same (basically) change, because I also need to have metadata passed along in order to support authorization middleware used in the command dispatch.

**Comment by dvic** [comment]
The only thing I might want to be optional:

> Also adds copying metadata from processed events to new commands by default.

**Comment by jwilger** [comment]
> The only thing I might want to be optional:
> 
> > Also adds copying metadata from processed events to new commands by default.

Good call. Perhaps when using handle/3 we could return commands as something like:

```
[some_command, {some_other_command, modified_metadata}, ...]
```

where the first one would just get the metadata copied over (as this PR does now), and the second command would allow you to modify that metadata first.

**Comment by jwilger** [comment]
@vheathen: what do you think about that suggestion? I realize it's been quite a while since you submitted the PR, would you want to make that change? If not, I'd be happy to pick it up and give it a go.

**Comment by vheathen** [comment]
@jwilger I was going to open a discussion about modifying metadata during the second iteration after this PR will be accepted (or rejected). I also thought to return a commands list exactly in the format you suggested above but just wanted to debate it with the community first: may be someone would offer a better approach. But I can add this functionality to the current PR if its ok.

@dvic About copying metadata to the issued commands by default: I was thinking that it is the most logical at least until it will be possible to modify metadata. May be I'm a little bit biased here, but I think that metadata is usually used to keep information which is not a part of the event (because it is outside of the domain itself) but is necessary to track commands-events chain (when relation/causation id are not enough) or for some technical reasons. As an example: we keep a tenant id in metadata, and the only reason we need it is technical, the subdomain knows nothing about tenants, and there is no sense to add a tenant id to every event and command. WDYT?

**Comment by dvic** [comment]
> @dvic About copying metadata to the issued commands by default: I was thinking that it is the most logical at least until it will be possible to modify metadata. May be I'm a little bit biased here, but I think that metadata is usually used to keep information which is not a part of the event (because it is outside of the domain itself) but is necessary to track commands-events chain (when relation/causation id are not enough) or for some technical reasons. As an example: we keep a tenant id in metadata, and the only reason we need it is technical, the subdomain knows nothing about tenants, and there is no sense to add a tenant id to every event and command. WDYT?

I can see the reasons for wanting to have the metadata passed along, I'm just not sure if it should be enabled by default. In our case, we solve the multi-tenancy by having separate event stores and commanded instances, but we definitely have use-cases for wanting to pass along the metadata or modifying it.

In any case, what about having an optional callback that determines the dispatched metadata (they `metadata` keyword of the dispatch function)?

```elixir
@callback dispatch_metadata(received_event :: event(), dispatched_commands :: [command()]) :: map()
```

**Comment by slashdotdash** [comment]
This change adds complexity to a the process manager with the overloading of the various callback functions. 

I would say that any information needed by a process manager (or aggregate) to make a decision should be included in the event payload, not metadata. Doing so makes this PR unnecessary as the relevant data would be accessible from the event. It is also simpler to have to only deal with events, not events and their associated metadata.

**Comment by vheathen** [comment]
@slashdotdash 

I would kindly ask to explain why do we have metadata at all then? Following that logic, we should put everything to the events themselves. 

I see metadata as a container for technical/supplementary data which don't have any sense in the domain but can be necessary for technical implementation or other needs. As an example, I will repeat from above: our events metadata got a tenant id, a timestamp of the moment when command was dispatched and an original user id. In many cases these fields don't have any sense in the domain as it knows nothing about tenants, users (because domain events have their actors inside - and only when they are necessary in terms of domain), timestamps, etc, and the reasons we need it: 

- a tenant id is to partition read model;
- a user id for ACL; 
- all of these fields including timestamp are necessary for debugging and auditing.

At any point in time, it is possible to get rid of the metadata and domain events will still make sense from the domain perspective. Two main places where metadata is used: in the projectors and in the ACL middleware. At the same time, we don't contaminate events with irrelevant _for the domain_ information.

So now we have a situation where manually dispatched commands are supplied with required metadata, directly resulting events have that metadata but subsequent commands after those events (and their events) from the process manager don't. Why?

Another thing is that process managers might need to modify that metadata - for example, to issue a command as a system user and not as an original user (or as nobody if it is not possible to copy that data from the original event). This PR didn't include any modification, only copying, but that can be useful as well and I had an intention to implement it after decision on the current one.

Also, the situations possible where it is necessary to keep state in the database because it's too large or complex or it is impossible to address things from the event itself - I don't like this approach, but already had a case where it was necessary to do this way at least during transition period (because of the legacy bad event design, but it is what it is). And - again, because of the technical reasons - metadata can be necessary to correctly access db.

I totally agree about aggregates: these are exclusively domain creatures, but process managers aren't, at least if we have an idea of metadata at all. Even when we speak about aggregates: they are copying metadata from commands to events. So why process managers (which are the opposite of aggregate in some sense) don't? 
Though the main difference between aggregates and PMs in terms of metadata is that metadata built before dispatching a command, so an aggregate don't need worry about it. The process manager dispatches commands though, so it also need to be able to build metadata. And to do so it needs old metadata access.

What do you think?

**Pull request merged**
