### PR TITLE
Add logging stacktrace to `handle_info`

### PR DESCRIPTION
**Pull request by kevinam99**
Aims to fix issue https://github.com/commanded/commanded/issues/523 to log the stacktrace which could give additional info.

### CODE REVIEW

**Comment by yordis** [comment]
Is there any way to combine it with the previous log? This will create another log entry.

**Comment by kevinam99** [comment]
Yes, that's a good suggestion. I just pushed it.

**Comment by kevinam99** [comment]
Anything else I could improve here?

**Comment by pirvudoru** [comment]
Hey @yordis do we need anything else to get this merged?

**Comment by pirvudoru** [comment]
@slashdotdash /  @dvic / @davydog187 can any of you help please getting this in ?

**Comment by davydog187** [comment]
I am not a maintainer nor is @dvic

**Comment by yordis** [comment]
Only Ben belongs to the organization

**Comment by edwardzhou** [comment]
> Only Ben belongs to the organization

The repo is quite long time no update. Would Ben invite someones in to helping the project move forward.

**Comment by slashdotdash** [comment]
We need at least one test to demonstrate the changes are working as expected before this can be merged.

**Comment by kevinam99** [comment]
> We need at least one test to demonstrate the changes are working as expected before this can be merged.

How could I go about doing this?

**Comment by yordis** [comment]
@kevinam99 check https://hexdocs.pm/ex_unit/1.12.3/ExUnit.CaptureLog.html

**Comment by slashdotdash** [comment]
The stacktrace was already being logged when an exception was rescued by an event handler when processing an event. 

I have now included the stacktrace in the error log statement in 69e9948dbf498c098ec9ee58aa22f934eb2a493a. Example logging output from the test suite shown below:

```
[error] Commanded.Event.ErrorEventHandler failed to handle event:
%Commanded.EventStore.RecordedEvent{
  event_id: "1d4f9c23-cf3b-4d13-b02a-7c2274af96ae",
  event_number: 1,
  stream_id: "a11d0ac6-0966-4cf5-9ffa-5d9ecb96996b",
  stream_version: 1,
  causation_id: "08508a33-5668-47cd-8922-e34dce57954b",
  correlation_id: "87c644fd-b1b4-4a43-be06-6ff6688ba364",
  event_type: "Elixir.Commanded.Event.ErrorAggregate.Events.ExceptionEvent",
  data: %Commanded.Event.ErrorAggregate.Events.ExceptionEvent{
    uuid: nil,
    strategy: nil,
    delay: nil,
    reply_to: '<0.416.0>'
  },
  metadata: %{},
  created_at: ~U[2024-01-09 15:49:16.050841Z]
}, due to:
** (RuntimeError) exception
    (commanded 1.4.2) test/event/support/error/error_event_handler.ex:23: Commanded.Event.ErrorEventHandler.handle/2
    (commanded 1.4.2) lib/commanded/event/handler.ex:952: Commanded.Event.Handler.delegate_event_to_handler/2
    (commanded 1.4.2) lib/commanded/event/handler.ex:894: Commanded.Event.Handler.handle_event/3
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded 1.4.2) lib/commanded/event/handler.ex:801: Commanded.Event.Handler.handle_info/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Pull request closed without merging**
