### PR TITLE
chore: remove asdf file

### PR DESCRIPTION
**Pull request by yordis**
Upgrading the latest version `asdf` (devtool only), so we can take advantage of latest tooling

### CODE REVIEW

**Comment by cdegroot** [comment]
I think it's useful to develop on the oldest supported Elixir and Erlang versions, but I also think that there's no formal support policy?

**Comment by yordis** [comment]
> I think it's useful to develop on the oldest supported Elixir and Erlang versions

Based on my experience maintaining other major organizations, I prefer to keep the CI current to see the problems as soon as possible or take advantage of it and follow https://hexdocs.pm/elixir/compatibility-and-deprecations.html to keep the matrix alive.

I only add things to the matrix when needed. Still, I fundamentally understand that I prefer to put enough trust in Elixir and OTP itself;

**Comment by drteeth** [comment]
Seems like most hex packages don't include .tool-versions leaving devs to take their own path here. I don't have a big preference either way.

It does seem like we could flesh out the test matrix though:
https://github.com/commanded/commanded/blob/master/.github/workflows/test.yml#L13

**Comment by yordis** [comment]
Based on my experience, `.tool-versions` is kept up to date and used in for formatting, listing, and things like that, using the `version-file` in `setup-beam`;

While some use matrixes for tests.

**Comment by drteeth** [comment]
This is not an academic point btw:
https://github.com/commanded/commanded/actions/runs/11319982776

**Comment by yordis** [comment]
> This is not an academic point btw:

I do not understand 😅. I am not making an argument for removing the matrix.

**Comment by drteeth** [comment]
Sorry, I just mean that we have actual problems introduced by newer versions of Elixir and OTP, this is to your point.

**Comment by yordis** [comment]
Should I close this?

**Comment by drteeth** [comment]
I can't decide what to do here. I'm tempted to remove it altogether or update it now that we have the matrix updated to cover the supported versions.

@cdegroot @jwilger ?

**Comment by yordis** [comment]
removed! this only affects people local development that are using `asdf`

**Comment by drteeth** [comment]
Add it to the git ignore file too?

**Comment by yordis** [comment]
done

**Comment by yordis** [comment]
ping

**Pull request merged**
